var animals_nature = {
    '🙈': 'see-no-evil monkey',
    '🙉': 'hear-no-evil monkey',
    '🙊': 'speak-no-evil monkey',
    '💥': 'collision',
    '💫': 'dizzy',
    '💦': 'sweat droplets',
    '💨': 'dashing away',
    '🐵': 'monkey face',
    '🐒': 'monkey',
    '🦍': 'gorilla',
    '🦧' : 'orangutan',
    '🐶': 'dog face',
    '🐕': 'dog',
    '🦮' : 'guide dog',
    '🐕‍🦺' : 'service dog',
    '🐩': 'poodle',
    '🐺': 'wolf',
    '🦊': 'fox',
    '🦝' : 'raccoon',
    '🐱': 'cat face',
    '🐈': 'cat',
    '🦁': 'lion',
    '🐯': 'tiger face',
    '🐅': 'tiger',
    '🐆': 'leopard',
    '🐴': 'horse face',
    '🐎': 'horse',
    '🦄': 'unicorn',
    '🦓': 'zebra',
    '🦌': 'deer',
    '🐮': 'cow face',
    '🐂': 'ox',
    '🐃': 'water buffalo',
    '🐄': 'cow',
    '🐷': 'pig face',
    '🐖': 'pig',
    '🐗': 'boar',
    '🐽': 'pig nose',
    '🐏': 'ram',
    '🐑': 'ewe',
    '🐐': 'goat',
    '🐪': 'camel',
    '🐫': 'two-hump camel',
    '🦙' : 'llama',
    '🦒': 'giraffe',
    '🐘': 'elephant',
    '🦏': 'rhinoceros',
    '🦛' : 'hippopotamus',
    '🐭': 'mouse face',
    '🐁': 'mouse',
    '🐀': 'rat',
    '🐹': 'hamster',
    '🐰': 'rabbit face',
    '🐇': 'rabbit',
    '🐿️' : 'chipmunk',
    '🦔': 'hedgehog',
    '🦇': 'bat',
    '🐻': 'bear',
    '🐻‍❄️': 'polar bear',
    '🐨': 'koala',
    '🐼': 'panda',
    '🦥' : 'sloth',
    '🦦' : 'otter',
    '🦨' : 'skunk',
    '🦘' : 'kangaroo',
    '🦡' : 'badger',
    '🐾': 'paw prints',
    '🦃': 'turkey',
    '🐔': 'chicken',
    '🐓': 'rooster',
    '🐣': 'hatching chick',
    '🐤': 'baby chick',
    '🐥': 'front-facing baby chick',
    '🐦': 'bird',
    '🐧': 'penguin',
    '🕊️' : 'dove',
    '🦅': 'eagle',
    '🦆': 'duck',
    '🦢' : 'swan',
    '🦉': 'owl',
    '🦩' : 'flamingo',
    '🦚' : 'peacock',
    '🦜' : 'parrot',
    '🐸': 'frog',
    '🐊': 'crocodile',
    '🐢': 'turtle',
    '🦎': 'lizard',
    '🐍': 'snake',
    '🐲': 'dragon face',
    '🐉': 'dragon',
    '🦕': 'sauropod',
    '🦖': 't-rex',
    '🐳': 'spouting whale',
    '🐋': 'whale',
    '🐬': 'dolphin',
    '🐟': 'fish',
    '🐠': 'tropical fish',
    '🐡': 'blowfish',
    '🦈': 'shark',
    '🐙': 'octopus',
    '🐚': 'spiral shell',
    '🐌': 'snail',
    '🦋': 'butterfly',
    '🐛': 'bug',
    '🐜': 'ant',
    '🐝': 'honeybee',
    '🐞': 'lady beetle',
    '🦗': 'cricket',
    '🕷️' : 'spider',
    '🕸️' : 'spider web',
    '🦂': 'scorpion',
    '🦟' : 'mosquito',
    '🦠' : 'microbe',
    '💐': 'bouquet',
    '🌸': 'cherry blossom',
    '💮': 'white flower',
    '🏵️' : 'rosette',
    '🌹': 'rose',
    '🥀': 'wilted flower',
    '🌺': 'hibiscus',
    '🌻': 'sunflower',
    '🌼': 'blossom',
    '🌷': 'tulip',
    '🌱': 'seedling',
    '🌲': 'evergreen tree',
    '🌳': 'deciduous tree',
    '🌴': 'palm tree',
    '🌵': 'cactus',
    '🌾': 'sheaf of rice',
    '🌿': 'herb',
    '☘️': 'shamrock',
    '🍀': 'four leaf clover',
    '🍁': 'maple leaf',
    '🍂': 'fallen leaf',
    '🍃': 'leaf fluttering in wind',
    '🍄': 'mushroom',
    '🌰': 'chestnut',
    '🦀': 'crab',
    '🦞' : 'lobster',
    '🦐': 'shrimp',
    '🦑': 'squid',
    '🌍': 'globe showing europe-africa',
    '🌎': 'globe showing americas',
    '🌏': 'globe showing asia-australia',
    '🌐': 'globe with meridians',
    '🌑': 'new moon',
    '🌒': 'waxing crescent moon',
    '🌓': 'first quarter moon',
    '🌔': 'waxing gibbous moon',
    '🌕': 'full moon',
    '🌖': 'waning gibbous moon',
    '🌗': 'last quarter moon',
    '🌘': 'waning crescent moon',
    '🌙': 'crescent moon',
    '🌚': 'new moon face',
    '🌛': 'first quarter moon face',
    '🌜': 'last quarter moon face',
    '☀️': 'sun',
    '🌝': 'full moon face',
    '🌞': 'sun with face',
    '⭐': 'star',
    '🌟': 'glowing star',
    '🌠': 'shooting star',
    '☁️': 'cloud',
    '⛅': 'sun behind cloud',
    '⛈️': 'cloud with lightning and rain',
    '🌤️' : 'sun behind small cloud',
    '🌥️' : 'sun behind large cloud',
    '🌦️' : 'sun behind rain cloud',
    '🌧️' : 'cloud with rain',
    '🌨️' : 'cloud with snow',
    '🌩️' : 'cloud with lightning',
    '🌪️' : 'tornado',
    '🌫️' : 'fog',
    '🌬️' : 'wind face',
    '🌈': 'rainbow',
    '☂️': 'umbrella',
    '☔': 'umbrella with rain drops',
    '⚡': 'high voltage',
    '❄️': 'snowflake',
    '☃️': 'snowman',
    '☄️': 'comet',
    '🔥': 'fire',
}

module.exports = animals_nature;